name: complex
on: push
jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - run: date
    windows:
        needs: [ubuntu]
        runs-on: windows-latest
        steps:
         - run: date
    macos:
        needs: [ubuntu, windows]
        runs-on: macos-latest
        steps:
        - run: date
    centos:
        needs: [ubuntu, windows, macos]
        runs-on: windows-latest
        steps:
        - run: date
